Apply dark theme on Windows if user enabled it in system settings.
opentrack/opentrack pull request #1169
Opened 2020-09-15 15:37 UTC by Slion

2020-09-17 23:16 UTC, Scx8R5SvSlYB3xcM0psn commented
Yes, I would like to have dark mode :-)

2020-09-18 01:06 UTC, sthalik requested changes

2020-09-20 11:25 UTC, Slion commented on gui/init.cpp
> +#ifdef Q_OS_WIN
Done

2020-09-21 01:07 UTC, merged

2020-09-21 01:07 UTC, sthalik commented
LGTM. 👍